{{- if .Values.registrySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    app: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .Values.registrySecret.dockerconfigjson }}
  .dockerconfigjson: {{ .Values.registrySecret.dockerconfigjson }}
  {{- else }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"palazspuskas\",\"password\":\"%s\"}}}" .Values.registrySecret.pat | b64enc }}
  {{- end }}
{{- end }}
